name: Update Custom RSS Feed

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour (UTC). Change timing if needed.
  workflow_dispatch:  # Enables manual runs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install feedparser requests

      - name: Run script
        run: python lewagon_news_only.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git add *.xml
          git commit -m "🔄 Auto-update RSS feed" || echo "No changes to commit"
          git push
