name: Update lewagon_news_only.xml hourly

on:
  schedule:
    - cron: '0 * * * *' # every hour
  workflow_dispatch:    # allow manual run too

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install feedparser html5lib

      - name: Run the feed filter script
        run: python filter_news_feed.py

      - name: Commit and push updated XML
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git add lewagon_news_only.xml
          git commit -m "⏰ Auto-update lewagon_news_only.xml" || echo "No changes to commit"
          git push "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:main
